export const FORTUNES = [
  "You’re meant for great things. Don’t forget that.",
    "Something beautiful is unfolding for you.",
    "The best chapters of your life haven’t been written yet.",
    "You’re closer than you think.",
    "Trust your timing. It’s working out.",
    "You’re becoming everything you once dreamed of.",
    "This is your soft launch into something big.",
    "Keep going. Future you is grateful.",
    "The universe loves a bold move.",
    "You’re building a life you won’t need a vacation from.",
    "The city you’re moving to is moving toward you too.",
    "A big change is waiting for you.",
    "You’re not lost. You’re just exploring.",
    "This move will make sense one day.",
    "You’ll meet your next best friend on Buddy.",
    "You won’t feel alone for long.",
    "You belong here.",
    "A random scroll might change your life.",
    "Someone will say, “I’m so glad we met.”",
    "Be a main character today.",
    "Someone’s about to match your vibe perfectly.",
    "A spontaneous plan will turn into a core memory.",
    "The right people will stay.",
    "Something fun is around the corner.",
    "Someone is looking for a friend like you.",
    "You will absolutely figure it out. Probably sooner than you think.",
    "Your social calendar is about to get busier.",
    "Warning: You may accidentally build a life you love."
];

