import type { BuddyIdentity } from "./buddyIdentity.types";

export const BUDDY_IDENTITIES: BuddyIdentity[] = [
  { id: "flat", label: "flat buddy" },
  { id: "gym", label: "gym buddy" },
  { id: "study", label: "study buddy" },
  { id: "commute", label: "commute buddy" },
  { id: "coffee", label: "coffee buddy" },
  { id: "walking", label: "walking buddy" },
  { id: "running", label: "running buddy" },
  { id: "weekend", label: "weekend-plan buddy" },
  { id: "travel", label: "travel buddy" },
  { id: "city", label: "city-exploring buddy" },
  { id: "hobby", label: "hobby buddy" },
  { id: "dance", label: "dance buddy" },
  { id: "cooking", label: "cooking buddy" },
  { id: "pet", label: "pet-sitting buddy" },
  { id: "language", label: "language-practice buddy" },
  { id: "chores", label: "chores buddy" },
  { id: "movie", label: "movie buddy" },
  { id: "game", label: "game-night buddy" },
  { id: "cowork", label: "co-working buddy" },
  { id: "morning", label: "morning-routine buddy" },
  { id: "event", label: "go-to-an-event buddy" },
  { id: "bookclub", label: "book-club buddy" },
  { id: "flathunt", label: "flat-hunting buddy" },
  { id: "drop", label: "drop-to-airport buddy" },
  { id: "plants", label: "plant-shopping buddy" },
  { id: "photo", label: "photo-walk buddy" },
  { id: "clean", label: "room-cleaning buddy" },
  { id: "break", label: "break-from-work buddy" },
  { id: "sip", label: "sip-and-paint buddy" },
  { id: "doctor", label: "doctor-visit buddy" },
  { id: "chai", label: "midnight-chai buddy" },
  { id: "grocery", label: "grocery-run buddy" },
  { id: "cafe", label: "cafe-hopping buddy" },
  { id: "rainy", label: "rainy-day-coffee buddy" },
  { id: "review", label: "flat-review buddy" },
  { id: "showcity", label: "show-your-city buddy" },
  { id: "hike", label: "weekend-hike buddy" },
  { id: "sports", label: "sports buddy" },
  { id: "thrift", label: "thrift-shopping buddy" },
  { id: "budget", label: "budget-planning buddy" },
  { id: "fitnessclass", label: "fitness-class buddy" },
  { id: "concert", label: "concert buddy" },
  { id: "workshop", label: "workshop buddy" },
  { id: "productivity", label: "productivity buddy" },
  { id: "sunset", label: "quiet-sunset buddy" },
];
export const IDENTITY_COLORS = [
  "#33ABFF",
  "#98D81E",
  "#F6D307",
  "#FFB9FF",
  "#8D8DFF",
];
