import type { BuddyIdentity } from "./buddyIdentity.types";

export const BUDDY_IDENTITIES: BuddyIdentity[] = [
  { id: "flat", label: "Flat Buddy" },
  { id: "gym", label: "Gym Buddy" },
  { id: "study", label: "Study Buddy" },
  { id: "commute", label: "Commute Buddy" },
  { id: "coffee", label: "Coffee Buddy" },
  { id: "walking", label: "Walking Buddy" },
  { id: "running", label: "Running Buddy" },
  { id: "weekend", label: "Weekend-plan Buddy" },
  { id: "travel", label: "Travel Buddy" },
  { id: "city", label: "City-exploring Buddy" },
  { id: "hobby", label: "Hobby Buddy" },
  { id: "dance", label: "Dance Buddy" },
  { id: "cooking", label: "Cooking Buddy" },
  { id: "pet", label: "Pet-sitting Buddy" },
  { id: "language", label: "Language-practice Buddy" },
  { id: "chores", label: "Chores Buddy" },
  { id: "movie", label: "Movie Buddy" },
  { id: "game", label: "Game-night Buddy" },
  { id: "cowork", label: "Co-working Buddy" },
  { id: "morning", label: "Morning-routine Buddy" },
  { id: "event", label: "Go-to-an-event Buddy" },
  { id: "bookclub", label: "Book-club Buddy" },
  { id: "flathunt", label: "Flat-hunting Buddy" },
  { id: "drop", label: "Drop-to-airport Buddy" },
  { id: "plants", label: "Plant-shopping Buddy" },
  { id: "photo", label: "Photo-walk Buddy" },
  { id: "clean", label: "Room-cleaning Buddy" },
  { id: "break", label: "Break-from-work Buddy" },
  { id: "sip", label: "Sip-and-paint Buddy" },
  { id: "doctor", label: "Doctor-visit Buddy" },
  { id: "chai", label: "Midnight-chai Buddy" },
  { id: "grocery", label: "Grocery-run Buddy" },
  { id: "cafe", label: "Cafe-hopping Buddy" },
  { id: "rainy", label: "Rainy-day-coffee Buddy" },
  { id: "review", label: "Flat-review Buddy" },
  { id: "showcity", label: "Show-your-city Buddy" },
  { id: "hike", label: "Weekend-hike Buddy" },
  { id: "sports", label: "Sports Buddy" },
  { id: "thrift", label: "Thrift-shopping Buddy" },
  { id: "budget", label: "Budget-planning Buddy" },
  { id: "fitnessclass", label: "Fitness-class Buddy" },
  { id: "concert", label: "Concert Buddy" },
  { id: "workshop", label: "Workshop Buddy" },
  { id: "productivity", label: "Productivity Buddy" },
  { id: "sunset", label: "Quiet-sunset Buddy" },
];
export const IDENTITY_COLORS = [
  "#33ABFF",
  "#98D81E",
  "#F6D307",
  "#FFB9FF",
  "#8D8DFF",
];
